# Generated by Django 4.0.4 on 2022-05-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='address',
        ),
    ]
